// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpocpsmjklnykrkrohwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwb2Nwc21qa2xueWtya3JvaHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzA0NDQsImV4cCI6MjA1OTk0NjQ0NH0.kg4D_rTGKCPXZAwHhq_4nBJ1pVw7MJDKy9mQfvMNUYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);